// NOTE: This file is generated by chored

ThisBuild / scalaVersion := "2.12.15"
ThisBuild / organization := "net.gfxmonk"
ThisBuild / homepage := Some(url(s"https://github.com/timbertson/sbt-strict-scope"))
ThisBuild / scmInfo := Some(
	ScmInfo(
		url("https://github.com/timbertson/sbt-strict-scope"),
		s"scm:git@github.com:timbertson/sbt-strict-scope.git"
	)
)
