// **NOTE**: this file is generated by `dhall-render`.
// You should NOT edit it manually, your changes will be lost.

addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.20")
Compile / unmanagedSourceDirectories += baseDirectory.value.getParentFile / "src" / "main" / "scala"

