// NOTE: This file is generated by chored

addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.20")
Compile / unmanagedSourceDirectories += baseDirectory.value.getParentFile / "src" / "main" / "scala"
